import {DEFAULTS} from '../src/config.js';
const $=selector=>document.querySelector(selector);
const sameBox=(a,b)=>['x','y','width','height'].every(key=>Math.abs(a[key]-b[key])<.1);
const opacityOnly=el=>el.getAnimations({subtree:true}).every(animation=>animation.effect.getKeyframes().every(frame=>Object.keys(frame).every(key=>['offset','computedOffset','easing','composite','opacity'].includes(key))));
export async function checkModernControls({check,wait,library:getLibrary,composer,modeLabel,enable,disable,voiceClicks,runtimeState}){
  let library=getLibrary();library.setConfig({...DEFAULTS});await wait(420);
  const svg=$('.native-wordmark'),mode=$('.mode-trigger'),arrow=mode.querySelector(':scope > svg'),sr=$('.mode-label .sr-only');
  const nativeBox=svg.getBoundingClientRect(),nativePaths=svg.innerHTML,arrowMarkup=arrow.outerHTML;
  let layer=$('[data-codex-tweaks-mb-svg-wordmark]');
  check('New native SVG wordmark receives a glyph-shaped layer, not the hidden label or arrow',library.getStatus().wordmarks===1&&svg.hasAttribute('data-codex-tweaks-mb-wordmark')&&!sr.hasAttribute('data-codex-tweaks-mb-wordmark')&&!arrow.hasAttribute('data-codex-tweaks-mb-wordmark')&&!!layer&&getComputedStyle(layer).display==='block'&&getComputedStyle(layer).maskImage.includes('data:image/svg+xml'));
  check('SVG decoration keeps native geometry, paths, accessibility label and arrow intact',svg.innerHTML===nativePaths&&sr.textContent==='Codex'&&arrow.outerHTML===arrowMarkup&&sameBox(nativeBox,layer.getBoundingClientRect())&&layer.getAttribute('aria-hidden')==='true'&&getComputedStyle(layer).pointerEvents==='none');
  check('Wordmark animates only a small fixed mask with no blur or canvas',opacityOnly(layer)&&getComputedStyle(layer).filter==='none'&&getComputedStyle(layer,'::after').filter==='none'&&!mode.querySelector('canvas'));
  library.setConfig({wordmarkHaze:false});
  check('Turning off SVG decoration restores the exact native logo without layout shift',!$('[data-codex-tweaks-mb-svg-wordmark]')&&sameBox(nativeBox,svg.getBoundingClientRect())&&svg.innerHTML===nativePaths&&svg.style.opacity==='');
  library.setConfig({wordmarkHaze:true});await wait(160);
  const old=svg;mode.click();$('[data-mode-option="ChatGPT"]').click();await wait(220);
  check('Changing product mode decorates the replacement SVG once and leaves menu labels native',$('.mode-label .sr-only').textContent==='ChatGPT'&&$('[data-codex-tweaks-mb-svg-wordmark]')&&document.querySelectorAll('[data-codex-tweaks-mb-svg-wordmark]').length===1&&!old.hasAttribute('data-codex-tweaks-mb-wordmark')&&!$('.mode-menu').querySelector('[data-codex-tweaks-mb-wordmark]'));
  layer=$('[data-codex-tweaks-mb-svg-wordmark]');const beforeMask=layer.style.maskImage,path=$('.native-wordmark path'),d=path.getAttribute('d');path.setAttribute('d','M0 0H12V24H0Z');await wait(100);
  check('An in-place native SVG path update refreshes the static mask',layer.style.maskImage!==beforeMask);path.setAttribute('d',d);await wait(100);
  modeLabel('Codex');await wait(200);
  const voice=$('.send'),mic=$('.voice'),voiceBox=voice.getBoundingClientRect(),voiceIcon=voice.querySelector('svg');
  check('Empty composer primary voice gets one small glow while dictation remains native',library.getStatus().voiceLights===1&&voice.hasAttribute('data-codex-tweaks-mb-voice')&&!voice.hasAttribute('data-codex-tweaks-mb-metal')&&!mic.hasAttribute('data-codex-tweaks-mb-voice')&&!mic.querySelector('.ctmb-voice-light')&&!voice.querySelector('canvas')&&voice.querySelectorAll('.ctmb-voice-light').length===1);
  const light=voice.querySelector('.ctmb-voice-light'),beforeOpacity=getComputedStyle(light,'::before').opacity,paint=getComputedStyle(light,'::before').backgroundImage;
  await wait(350);
  check('Idle voice uses only opacity breathing on unchanged paint',getComputedStyle(light,'::before').opacity!==beforeOpacity&&getComputedStyle(light,'::before').backgroundImage===paint&&getComputedStyle(light,'::before').filter==='none'&&opacityOnly(light));
  const clickCount=voiceClicks();voice.click();await wait(100);
  check('Native primary voice click and icon are preserved',voiceClicks()===clickCount+1&&voice.querySelector('svg')===voiceIcon&&sameBox(voiceBox,voice.getBoundingClientRect()));
  voice.disabled=true;await wait(140);check('Disabled primary voice retains native appearance and no animation',!voice.querySelector('.ctmb-voice-light'));voice.disabled=false;await wait(140);
  voice.setAttribute('aria-pressed','true');await wait(140);check('Active voice does not retain an idle-ready glow',!voice.querySelector('.ctmb-voice-light'));voice.removeAttribute('aria-pressed');await wait(140);
  const draft=$('.message');draft.value='Test state transition';draft.dispatchEvent(new Event('input',{bubbles:true}));await wait(350);
  check('Typing replaces voice glow with Send metal without duplicate decoration',voice.hasAttribute('data-codex-tweaks-mb-metal')&&!voice.hasAttribute('data-codex-tweaks-mb-voice')&&!voice.querySelector('.ctmb-voice-light')&&voice.querySelectorAll('.ctmb-metal-mount').length===1&&sameBox(voiceBox,voice.getBoundingClientRect()));
  voice.click();await wait(200);
  check('Running changes to Stop while preserving one metal mount',library.getStatus().running&&voice.getAttribute('aria-label')==='Stop generating'&&!voice.querySelector('.ctmb-voice-light')&&voice.querySelectorAll('.ctmb-metal-mount').length===1);
  voice.click();draft.value='';draft.dispatchEvent(new Event('input',{bubbles:true}));await wait(220);
  check('Clearing the draft restores voice glow and releases Send material',voice.hasAttribute('data-codex-tweaks-mb-voice')&&!voice.hasAttribute('data-codex-tweaks-mb-metal')&&!voice.querySelector('.ctmb-metal-mount')&&voice.querySelectorAll('.ctmb-voice-light').length===1&&sameBox(voiceBox,voice.getBoundingClientRect()));
  composer(true);await wait(200);check('Home voice label is supported without decorating the account voice control',library.getStatus().voiceLights===1&&$('.send').getAttribute('aria-label')==='开始新的语音聊天'&&!$('.footer-voice').hasAttribute('data-codex-tweaks-mb-voice'));
  library.setConfig({broad:false,beam:false,modelHaze:false});await wait(350);
  const simple=runtimeState(),scans=library.getStatus().scans,wordLayer=$('[data-codex-tweaks-mb-svg-wordmark]'),wordOpacity=getComputedStyle(wordLayer,'::after').opacity;
  await wait(360);
  check('SVG and voice alone keep moving with no material draws or target scans',simple.instances===0&&runtimeState().frames===simple.frames&&runtimeState().directFrames===simple.directFrames&&library.getStatus().scans===scans&&getComputedStyle(wordLayer,'::after').opacity!==wordOpacity&&!runtimeState().loopScheduled);
  library.setConfig({motion:false});await wait(100);const frozen=getComputedStyle(wordLayer,'::after').opacity;
  await wait(180);
  check('Pause freezes SVG and voice opacity animation',getComputedStyle(wordLayer,'::after').opacity===frozen&&getComputedStyle($('.ctmb-voice-light'),'::before').animationPlayState==='paused');
  library.setConfig({motion:true});
  const focusDescriptor=Object.getOwnPropertyDescriptor(document,'hasFocus');
  try{
    Object.defineProperty(document,'hasFocus',{configurable:true,value:()=>false});window.dispatchEvent(new FocusEvent('blur'));await wait(120);
    check('Blur pauses the new SVG and voice effects too',getComputedStyle(wordLayer,'::after').animationPlayState==='paused'&&getComputedStyle($('.ctmb-voice-light'),'::before').animationPlayState==='paused');
  }finally{if(focusDescriptor)Object.defineProperty(document,'hasFocus',focusDescriptor);else delete document.hasFocus;window.dispatchEvent(new FocusEvent('focus'));}
  await wait(120);
  check('Focus resumes SVG and voice without replacing their layers',wordLayer===$('[data-codex-tweaks-mb-svg-wordmark]')&&getComputedStyle(wordLayer,'::after').animationPlayState==='running'&&getComputedStyle($('.ctmb-voice-light'),'::before').animationPlayState==='running');
  document.documentElement.dataset.theme='light';await wait(180);
  check('Light theme updates both effects without changing native geometry',wordLayer.getAttribute('data-codex-tweaks-mb-svg-wordmark')==='light'&&$('.send').getAttribute('data-codex-tweaks-mb-voice')==='light'&&sameBox($('.native-wordmark').getBoundingClientRect(),wordLayer.getBoundingClientRect()));
  const nativeSvg=$('.native-wordmark'),nativeVoice=$('.send'),savedSvg=nativeSvg.innerHTML;
  disable();await wait(80);
  check('Cleanup removes SVG and voice layers and restores native styles',!$('[data-codex-tweaks-mb-svg-wordmark],.ctmb-voice-light,[data-codex-tweaks-mb-voice],[data-codex-tweaks-mb-voice-paused]')&&nativeSvg.innerHTML===savedSvg&&nativeSvg.parentElement.style.position===''&&nativeVoice.style.position===''&&getComputedStyle(nativeVoice).position==='static');
  const label=$('.mode-label'),nativeChildren=[...label.childNodes];label.replaceChildren();enable();library=getLibrary();await wait(120);
  check('Missing SVG heading does not decorate empty controls',library.getStatus().wordmarks===0);
  label.append(...nativeChildren);await wait(180);
  check('A late-mounted SVG heading is detected without another user action',library.getStatus().wordmarks===1&&!!$('[data-codex-tweaks-mb-svg-wordmark]'));
  library.setConfig({...DEFAULTS});document.documentElement.dataset.theme='dark';await wait(250);
  check('Reactivation creates one SVG and one voice layer',document.querySelectorAll('[data-codex-tweaks-mb-svg-wordmark]').length===1&&document.querySelectorAll('.ctmb-voice-light').length===1);
}
